
title: Młodzi w Równowadze
email: kontakt@mlodziwrownowadze.live
description: Strona projektu społecznego Młodzi w Równowadze
baseurl: ""
url: "https://www.mlodziwrownowadze.live/"
author:
  name: "lodyczekoladowe"
  email: "kontakt@mlodziwrownowadze.live"

github_username: mlodzi-w-rownowadze
instagram_username: mlodzi.w.rownowadze
facebook_username: mlodziwrownowadze

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

sass:
  load_paths:
    - "node_modules"
  sass_dir: assets/css
  style: compressed
  input: assets/css/main.scss
  output: assets/css/main.css


plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - ./_plugins/date_filter.rb

collections:
  pages:
    output: true