
title: Młodzi w Równowadze
email: kontakt@mlodziwrownowadze.live
description: Strona projektu społecznego Młodzi w Równowadze
baseurl: ""
url: "https://www.mlodziwrownowadze.live/"
author:
  name: "lodyczekoladowe"
  email: "kontakt@mlodziwrownowadze.live"

github_username: mlodzi-w-rownowadze

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

sass:
  load_paths:
    - "node_modules"
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - ./plugins/date_filter.rb

collections:
  pages:
    output: true